# .tekton/pipeline.yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-pipeline
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    tasks:
      - name: git-clone
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              # OLD reference - Renovate should update this
              value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone:0.1@sha256:eeac8b6432f2e8e9b319572afeef51f225f443af80d9ead5916d7309f534cf3b
            - name: name
              value: git-clone
            - name: kind
              value: task

      - name: buildah
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              # OLD reference - Renovate should update this
              value: quay.io/redhat-appstudio-tekton-catalog/task-buildah:0.7@sha256:745d799b67f799beac48c514a34fcbe853bf52a8b40e5d31107bac7c22a458bc
            - name: name
              value: buildah
            - name: kind
              value: task
        runAfter:
          - git-clone
